[Interface]
Address = 10.7.0.2/24
DNS = 192.168.150.36
PrivateKey = IAJY9+BsAZjf8sv7a+BzKhTK9KVpsmEuAF5joAcf6l4=

[Peer]
PublicKey = U0MhENi1BamBrkBPiaLoFtRlWDfSSrY4NJbF2T6KxEQ=
PresharedKey = Jt+pYrXfjJfrIhS0oa+/beB8cQGCFMPqNuv9nxgfAIg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 37.18.93.12:51820
PersistentKeepalive = 25
